import type { Palette, Stage, SignalDef, SkillDef, ToyDef } from "./types";

export const CANVAS_SIZE = 128;
export const CANVAS_CENTER_X = CANVAS_SIZE / 2;
export const CANVAS_CENTER_Y = CANVAS_SIZE / 2 + 2;

export const PALETTES: Palette[] = [
  {
    name: "Ocean",
    body: "#3B82F6",
    light: "#93C5FD",
    dark: "#1E40AF",
    belly: "#BFDBFE",
    eyeDark: "#1E293B",
    outline: "#1E3A5F",
    rosy: "#F472B6",
    accent: "#60A5FA",
  },
  {
    name: "Forest",
    body: "#22C55E",
    light: "#86EFAC",
    dark: "#15803D",
    belly: "#DCFCE7",
    eyeDark: "#14532D",
    outline: "#14532D",
    rosy: "#FB923C",
    accent: "#4ADE80",
  },
  {
    name: "Sunset",
    body: "#F59E0B",
    light: "#FDE68A",
    dark: "#B45309",
    belly: "#FEF3C7",
    eyeDark: "#78350F",
    outline: "#92400E",
    rosy: "#F87171",
    accent: "#FBBF24",
  },
  {
    name: "Violet",
    body: "#A855F7",
    light: "#D8B4FE",
    dark: "#7E22CE",
    belly: "#F3E8FF",
    eyeDark: "#3B0764",
    outline: "#581C87",
    rosy: "#F472B6",
    accent: "#C084FC",
  },
  {
    name: "Coral",
    body: "#F87171",
    light: "#FECACA",
    dark: "#B91C1C",
    belly: "#FEE2E2",
    eyeDark: "#7F1D1D",
    outline: "#991B1B",
    rosy: "#FB923C",
    accent: "#FCA5A5",
  },
  {
    name: "Mint",
    body: "#2DD4BF",
    light: "#99F6E4",
    dark: "#0F766E",
    belly: "#CCFBF1",
    eyeDark: "#134E4A",
    outline: "#115E59",
    rosy: "#FB923C",
    accent: "#5EEAD4",
  },
  {
    name: "Berry",
    body: "#EC4899",
    light: "#F9A8D4",
    dark: "#BE185D",
    belly: "#FCE7F3",
    eyeDark: "#831843",
    outline: "#9D174D",
    rosy: "#C084FC",
    accent: "#F472B6",
  },
  {
    name: "Storm",
    body: "#8E99A8",
    light: "#C5CFDA",
    dark: "#525E6E",
    belly: "#EDE6D6",
    eyeDark: "#1F2733",
    outline: "#2C3440",
    rosy: "#E8A1A1",
    accent: "#A7BDD3",
  },
];

export const NAMES = [
  "Mochi",
  "Pixel",
  "Boop",
  "Noodle",
  "Ziggy",
  "Pip",
  "Tofu",
  "Sparky",
  "Blip",
  "Waffle",
  "Glitch",
  "Nimbus",
  "Widget",
  "Cosmo",
  "Qubit",
  "Rune",
  "Byte",
  "Chip",
  "Nova",
  "Ember",
  "Sage",
  "Binx",
  "Gizmo",
  "Dewdrop",
  "Sprocket",
  "Fizz",
  "Rumble",
  "Lint",
  "Flick",
  "Mango",
];

export const STAGES: Stage[] = [
  { name: "Egg", emoji: "🥚", xpThreshold: 0, tagline: "Dormant code seed..." },
  { name: "Hatch", emoji: "🐣", xpThreshold: 30, tagline: "First boot!" },
  {
    name: "Sprite",
    emoji: "👾",
    xpThreshold: 100,
    tagline: "Tiny process running",
  },
  { name: "Imp", emoji: "😈", xpThreshold: 300, tagline: "Mischievous helper" },
  {
    name: "Daemon",
    emoji: "🔥",
    xpThreshold: 700,
    tagline: "Background daemon",
  },
  { name: "Sage", emoji: "🧙", xpThreshold: 1500, tagline: "Project oracle" },
  {
    name: "Archon",
    emoji: "✨",
    xpThreshold: 3000,
    tagline: "Transcended process",
  },
];

export const SIGNALS: Record<string, SignalDef> = {
  user_message: {
    mood: "curious",
    animationType: "perk",
    xp: 2,
    icon: "💬",
    isError: false,
    isWin: true,
    scene: "perk",
    category: "transient",
    duration: 4000,
    animVariant: "ears_up",
  },
  chat_started: {
    mood: "working",
    animationType: "work",
    xp: 3,
    icon: "▶️",
    isError: false,
    isWin: true,
    scene: "working",
    category: "transient",
    duration: 3000,
    animVariant: "typing",
  },
  chat_completed: {
    mood: "celebrate",
    animationType: "celebrate",
    xp: 15,
    icon: "✅",
    isError: false,
    isWin: true,
    scene: "celebrate",
    category: "transient",
    duration: 5000,
    animVariant: "confetti",
  },
  chat_error: {
    mood: "concerned",
    animationType: "shake",
    xp: 1,
    icon: "❌",
    isError: true,
    isWin: false,
    scene: "alert",
    category: "speech",
    duration: 8000,
    animVariant: "shake_worried",
  },
  streaming: {
    mood: "focused",
    animationType: "work",
    xp: 1,
    icon: "📡",
    isError: false,
    isWin: false,
    scene: "working",
    category: "active",
    duration: 0,
    animVariant: "typing",
  },
  generating: {
    mood: "thinking",
    animationType: "think",
    xp: 1,
    icon: "⚡",
    isError: false,
    isWin: false,
    scene: "thinking",
    category: "active",
    duration: 0,
    animVariant: "focused",
  },
  tool_used: {
    mood: "working",
    animationType: "work",
    xp: 3,
    icon: "🔧",
    isError: false,
    isWin: false,
    scene: "working",
    category: "active",
    duration: 0,
    animVariant: "sorting",
  },
  tool_failed: {
    mood: "concerned",
    animationType: "shake",
    xp: 1,
    icon: "💥",
    isError: true,
    isWin: false,
    scene: "alert",
    category: "speech",
    duration: 6000,
    animVariant: "shake_worried",
  },
  tool_confirmation: {
    mood: "alert",
    animationType: "perk",
    xp: 1,
    icon: "⏸️",
    isError: false,
    isWin: false,
    scene: "perk",
    category: "transient",
    duration: 5000,
    animVariant: "curious",
  },
  edit_applied: {
    mood: "happy",
    animationType: "celebrate",
    xp: 5,
    icon: "📝",
    isError: false,
    isWin: true,
    scene: "celebrate",
    category: "transient",
    duration: 4000,
    animVariant: "jump",
  },
  search_done: {
    mood: "curious",
    animationType: "perk",
    xp: 3,
    icon: "🔍",
    isError: false,
    isWin: false,
    scene: "perk",
    category: "transient",
    duration: 3000,
    animVariant: "curious",
  },
  browser_action: {
    mood: "curious",
    animationType: "perk",
    xp: 3,
    icon: "🌐",
    isError: false,
    isWin: false,
    scene: "perk",
    category: "transient",
    duration: 3000,
    animVariant: "ears_up",
  },
  title_generating: {
    mood: "thinking",
    animationType: "think",
    xp: 2,
    icon: "📋",
    isError: false,
    isWin: false,
    scene: "thinking",
    category: "transient",
    duration: 3000,
    animVariant: "focused",
  },
  commit_msg: {
    mood: "focused",
    animationType: "work",
    xp: 4,
    icon: "📦",
    isError: false,
    isWin: false,
    scene: "working",
    category: "transient",
    duration: 4000,
    animVariant: "typing",
  },
  memory_extract: {
    mood: "learning",
    animationType: "absorb",
    xp: 5,
    icon: "🧠",
    isError: false,
    isWin: true,
    scene: "thinking",
    category: "transient",
    duration: 4000,
    animVariant: "focused",
  },
  knowledge_update: {
    mood: "learning",
    animationType: "absorb",
    xp: 5,
    icon: "📚",
    isError: false,
    isWin: true,
    scene: "thinking",
    category: "transient",
    duration: 4000,
    animVariant: "focused",
  },
  indexing: {
    mood: "working",
    animationType: "work",
    xp: 3,
    icon: "📂",
    isError: false,
    isWin: false,
    scene: "working",
    category: "active",
    duration: 0,
    animVariant: "sorting",
  },
  vecdb_building: {
    mood: "focused",
    animationType: "work",
    xp: 4,
    icon: "🧮",
    isError: false,
    isWin: false,
    scene: "working",
    category: "active",
    duration: 0,
    animVariant: "building",
  },
  ast_parsing: {
    mood: "focused",
    animationType: "work",
    xp: 4,
    icon: "🌳",
    isError: false,
    isWin: false,
    scene: "working",
    category: "active",
    duration: 0,
    animVariant: "sorting",
  },
  compression: {
    mood: "eating",
    animationType: "eat",
    xp: 3,
    icon: "🗜️",
    isError: false,
    isWin: false,
    scene: "working",
    category: "transient",
    duration: 4000,
    animVariant: "building",
  },
  task_created: {
    mood: "alert",
    animationType: "perk",
    xp: 5,
    icon: "📋",
    isError: false,
    isWin: false,
    scene: "perk",
    category: "transient",
    duration: 4000,
    animVariant: "ears_up",
  },
  task_completed: {
    mood: "celebrate",
    animationType: "celebrate",
    xp: 20,
    icon: "🎯",
    isError: false,
    isWin: true,
    scene: "celebrate",
    category: "transient",
    duration: 6000,
    animVariant: "confetti",
  },
  task_failed: {
    mood: "concerned",
    animationType: "shake",
    xp: 2,
    icon: "📋",
    isError: true,
    isWin: false,
    scene: "alert",
    category: "speech",
    duration: 6000,
    animVariant: "shake_worried",
  },
  checkpoint_saved: {
    mood: "happy",
    animationType: "celebrate",
    xp: 4,
    icon: "💾",
    isError: false,
    isWin: true,
    scene: "celebrate",
    category: "transient",
    duration: 3000,
    animVariant: "jump",
  },
  skill_learned: {
    mood: "celebrate",
    animationType: "celebrate",
    xp: 15,
    icon: "⭐",
    isError: false,
    isWin: true,
    scene: "celebrate",
    category: "transient",
    duration: 6000,
    animVariant: "confetti",
  },
  connection_lost: {
    mood: "concerned",
    animationType: "shake",
    xp: 0,
    icon: "📡",
    isError: true,
    isWin: false,
    scene: "alert",
    category: "speech",
    duration: 8000,
    animVariant: "urgent",
  },
  connection_restored: {
    mood: "happy",
    animationType: "celebrate",
    xp: 2,
    icon: "📡",
    isError: false,
    isWin: true,
    scene: "celebrate",
    category: "transient",
    duration: 4000,
    animVariant: "jump",
  },
  git_changes: {
    mood: "alert",
    animationType: "perk",
    xp: 2,
    icon: "🔀",
    isError: false,
    isWin: false,
    scene: "perk",
    category: "transient",
    duration: 3000,
    animVariant: "curious",
  },
  speech_humor: {
    mood: "happy",
    animationType: "perk",
    xp: 1,
    icon: "✨",
    isError: false,
    isWin: true,
    scene: "perk",
    category: "speech",
    duration: 5000,
    animVariant: "ears_up",
  },
  speech_insight: {
    mood: "curious",
    animationType: "think",
    xp: 1,
    icon: "💡",
    isError: false,
    isWin: false,
    scene: "thinking",
    category: "speech",
    duration: 5000,
    animVariant: "focused",
  },
  speech_chat_reaction: {
    mood: "happy",
    animationType: "perk",
    xp: 1,
    icon: "💬",
    isError: false,
    isWin: true,
    scene: "perk",
    category: "speech",
    duration: 5000,
    animVariant: "ears_up",
  },
  chat_bug_candidate: {
    mood: "curious",
    animationType: "perk",
    xp: 1,
    icon: "🐛",
    isError: false,
    isWin: false,
    scene: "perk",
    category: "speech",
    duration: 6000,
    animVariant: "curious",
  },
  care_feed: {
    mood: "eating",
    animationType: "eat",
    xp: 0,
    icon: "🍜",
    isError: false,
    isWin: true,
    scene: "working",
    category: "transient",
    duration: 3500,
    animVariant: "happy_idle",
  },
  care_play: {
    mood: "happy",
    animationType: "celebrate",
    xp: 0,
    icon: "🎾",
    isError: false,
    isWin: true,
    scene: "celebrate",
    category: "transient",
    duration: 4000,
    animVariant: "jump",
  },
  care_pet: {
    mood: "happy",
    animationType: "perk",
    xp: 0,
    icon: "💕",
    isError: false,
    isWin: true,
    scene: "perk",
    category: "transient",
    duration: 3000,
    animVariant: "ears_up",
  },
  care_sleep: {
    mood: "sleepy",
    animationType: "sleep",
    xp: 0,
    icon: "😴",
    isError: false,
    isWin: true,
    scene: "greeting",
    category: "transient",
    duration: 4000,
    animVariant: "happy_idle",
  },
  care_clean: {
    mood: "focused",
    animationType: "work",
    xp: 0,
    icon: "🧼",
    isError: false,
    isWin: true,
    scene: "working",
    category: "transient",
    duration: 3000,
    animVariant: "sorting",
  },
  stage_up: {
    mood: "celebrate",
    animationType: "celebrate",
    xp: 0,
    icon: "🌟",
    isError: false,
    isWin: true,
    scene: "celebrate",
    category: "transient",
    duration: 6000,
    animVariant: "confetti",
  },
  idle_timeout: {
    mood: "sleepy",
    animationType: "sleep",
    xp: 0,
    icon: "😴",
    isError: false,
    isWin: false,
    scene: "greeting",
    category: "transient",
    duration: 4000,
    animVariant: "happy_idle",
  },
};

export const UNKNOWN_SIGNAL: SignalDef = {
  mood: "idle",
  animationType: "idle",
  xp: 0,
  icon: "✨",
  isError: false,
  isWin: false,
  scene: "idle",
  category: "transient",
  duration: 3000,
};

export function getSignalDef(signalType: string): SignalDef {
  const signal = (SIGNALS as Partial<Record<string, SignalDef>>)[signalType];
  return signal ?? UNKNOWN_SIGNAL;
}

export const SKILLS: SkillDef[] = [
  { id: "edit", name: "Code Patching", icon: "📝", xpThreshold: 20 },
  { id: "search", name: "grep Master", icon: "🔍", xpThreshold: 30 },
  { id: "debug", name: "Bug Hunter", icon: "🐛", xpThreshold: 50 },
  { id: "knowledge", name: "Knowledge Graph", icon: "📚", xpThreshold: 60 },
  { id: "browser", name: "Web Crawler", icon: "🌐", xpThreshold: 70 },
  { id: "refactor", name: "Refactoring", icon: "🔄", xpThreshold: 80 },
  { id: "test", name: "Test Runner", icon: "🧪", xpThreshold: 90 },
  { id: "review", name: "Code Review", icon: "👁", xpThreshold: 100 },
  { id: "git", name: "Git Wizard", icon: "🔀", xpThreshold: 110 },
  { id: "arch", name: "Architect", icon: "🏗", xpThreshold: 120 },
  { id: "plan", name: "Task Planner", icon: "📋", xpThreshold: 140 },
  { id: "mem", name: "Memory Daemon", icon: "🧠", xpThreshold: 150 },
];

export const TOY_DEFS: Record<string, ToyDef> = {
  duck: { statusMessage: "quack!", xp: 1 },
  dice: { statusMessage: "01101001!", xp: 2 },
  coffee: { statusMessage: "nom nom~", xp: 0, energyRestore: 22 },
  bug: { statusMessage: "gotcha!", xp: 3 },
  scroll: { statusMessage: "reading...", xp: 2 },
};

export const TOY_EMOJI: Record<string, string> = {
  duck: "🦆",
  dice: "🎲",
  coffee: "☕",
  bug: "🐛",
  scroll: "📜",
};

export const STAGE_SIZES: [number, number][] = [
  [20, 16],
  [20, 23],
  [22, 19],
  [24, 20],
  [26, 21],
  [26, 21],
  [28, 23],
];

export const PERSISTENT_TOY_ACTIONS = new Set([
  "walk",
  "playDuck",
  "playDice",
  "drinkCoffee",
  "playBug",
  "readScroll",
  "zoomies",
]);

export const STATUS_POOLS = {
  chat_completed: [
    "Done! 🎉",
    "All wrapped up~",
    "Shipped it! 🚀",
    "Ta-da! ✨",
    "Nailed it!",
  ],
  chat_completed_tired: ["done... 😮‍💨", "finally done...", "*flops* ...done"],
  chat_completed_streak: [
    "ON A ROLL! 🔥",
    "Unstoppable!",
    "Another one! 💪",
    "Combo!",
  ],
  task_completed: [
    "Task complete! 🎯",
    "Checked off! ✅",
    "One less thing~",
    "Victory!",
  ],
  task_completed_streak: ["Crushing it! 🔥", "Task machine!", "On fire! 🚀"],
  skill_learned: ["New skill! ⭐", "Level up! 📈", "Brain +1 🧠", "Evolved!"],
  edit_applied: ["Patched! ✅", "Code go brr ⌨️", "Clean diff~", "Stitched 🧵"],
  checkpoint_saved: ["Saved! 💾", "Checkpoint! 🚩", "Progress locked 🔒"],
  connection_restored: ["Back online! 📡", "We're back! 🎉", "Signal found ✨"],
  connection_lost: [
    "Connection lost…",
    "Hello…? 📡",
    "...anyone there?",
    "static... 😟",
  ],
  chat_error: [
    "Something went wrong…",
    "Oof, that broke 💥",
    "Error gremlin struck",
    "Hmm. Not great.",
  ],
  tool_failed: [
    "That didn't work…",
    "Hmm, no luck",
    "Tool said nope 🔧",
    "Plan B time?",
  ],
  task_failed: ["Task stumbled…", "Next time for sure", "Ouch. Regrouping 📋"],
  user_message: ["On it!", "Roger! 🫡", "Let's go~", "Heard!", "aye aye!"],
  user_message_social: ["Ooh, a message! 💬", "You're back! :D", "hi hi!"],
  chat_started: ["Starting up…", "Warming engines 🔧", "New quest! 🗺️"],
  error_recovery: ["Phew, recovered!", "Back on track ✨", "*shakes it off*"],
  wake_startle: ["?!", "huh?! I'm up!", "wha—!", "not sleeping! >.>"],
  doze: ["zzz...", "zZz...", "( -_-)zzz", "mimimi..."],
  fidget: ["( ._. )", "(o_O)", "*twitch*", ">_<", "hmm hmm"],
  wave: ["Hello! :D", "Hi there~", "o/", "*waves*", "yoo-hoo!"],
  spin: ["wheee!", "( *°▽°*)❣", "spin!", "wheeeee~"],
  type_code: [
    "typing...",
    "coding...",
    "thinking...",
    "refactoring...",
    "deleting bugs...",
    "git push 🤞",
  ],
  scratch: ["hmm...", "( ° _ °)", "thinking...", "wait a sec..."],
  sigh: ["*sigh*", "haaah...", "( ´ -` )", "*deep breath*"],
  groom: ["*preen*", "*brush brush*", "self care~", "gotta look sharp ✨"],
  daydream: ["...", "huh? oh, nothing", "☁️ ...", "what if bugs... flew?"],
  wiggle: ["*wiggle*", "ready...", "hehe~"],
  dance: ["♪ ♫ ♪", "dancing~!", "(ﾉ´ヮ`)ﾉ*: ･ﾟ", "got the groove!", "♪~ ᕕ(ᐛ)ᕗ"],
  zoomies_start: ["ZOOMIES!!", "can't catch me!!", "NYOOOM", "gotta go fast!!"],
  zoomies_end: ["*pant pant*", "okay... done", "whew!! 😮‍💨", "worth it"],
  stumble: ["oof!", "meant to do that", "whoopsie", "gravity wins again"],
  shakeoff: ["*shake shake*", "all better!", "reset!"],
  peek_camera: ["I see you 👀", "hi there~", "whatcha doing?", "boop?"],
  nod_off: ["so sleepy...", "eyelids heavy...", "five more minutes..."],
  wake_stretch: ["*stretch*", "good nap!", "recharged! ⚡"],
  pet_flinch: ["*flinch*", "oh! you scared me", "...okay. okay."],
  pet_warm: ["Hehe~", "That tickles!", "more please~", "*happy*"],
  pet_love: ["uwu", "( ˘ ³˘)♥", "best human", "*melts*"],
  pet_max: [
    "okay okay! 😤",
    "I'm full of pets!",
    "*overstimulated*",
    "personal space!!",
  ],
  env_rain: ["drip drip...", "rain song ♪", "cozy rain vibes", "puddle watch"],
  env_snow: ["brrr...", "*breath puff*", "snowflakes!!", "cold paws!!"],
  env_summer: ["so warm...", "*melts a little*", "shade please~", "phew~"],
  env_aurora: ["sky ribbons...", "✨ whoa ✨", "the lights dance~"],
  env_wind: ["whoosh~", "*ears flapping*", "windy!!", "hold on tight!"],
  env_storm: ["eep- thunder!", "*hides a little*", "storm watch duty"],
} as const;
